---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-testing
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nginx-php:testing .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-php:testing
  - docker tag pdr.nephatrine.net/nephatrine/nginx-php:testing nephatrine/nginx-php:testing
  - HOME=/mnt/config/home docker push nephatrine/nginx-php:testing
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-php:testing

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 6e3dac2d70dc96b3aa119eabba8e9c19b9fbace8b548d0b16e3be93ea6445601

...
