---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-7
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nginx-php:7 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-php:7
  - docker tag pdr.nephatrine.net/nephatrine/nginx-php:7 nephatrine/nginx-php:7
  - HOME=/mnt/config/home docker push nephatrine/nginx-php:7
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-php:7

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: ddc2f5996456340747cb2d7c61027c30372de8764d989470adbb018e62b0491e

...
